theme: jekyll-theme-minimal
title: CIT 281 - Lab 9
description: Created Learning Lab course/repo within your GitHub account, practiced exiting and returning to the course from course repo, worked through course, downloaded completed course repo as deliverable.
